name: Build Result

on:
  push:
    branches:
      - main
    paths: 
      - 'result/**' 
      - '.github/workflows/result-ci.yaml'

  pull_request:
    branches:
      - main
    paths: 
      - 'result/**' 
      - '.github/workflows/result-ci.yaml'

env:
  PROJECT_ID: "project-18ee516c-a108-431d-a73"
  REGION: asia-south1
  REPOSITORY: vote-docker-repo
  IMAGE_NAME: result
  IMAGE_TAG: ${{ github.sha }}

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./result/package-lock.json

      - name: Install Dependencies
        working-directory: ./result
        run: npm ci

      # - name: Run Lint
      #   working-directory: ./result
      #   run: npm run lint

      - name: Run Unit Tests
        working-directory: ./result
        run: npm test


  build-scan-push-sign:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/440909314761/locations/global/workloadIdentityPools/platform-github-pool/providers/github-provider
          service_account: github-actions@project-18ee516c-a108-431d-a73.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
      
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Docker Image 
        uses: docker/build-push-action@v6 
        with: 
          context: ./result 
          push: true 
          tags: | 
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} 
          cache-from: type=gha 
          cache-to: type=gha,mode=max

      # - name: Build Docker Image
      #   working-directory:  ./result
      #   run: |
      #     docker build \
      #       -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG \
      #       .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      # - name: Push Docker Image
      #   run: |
      #     docker push \
      #       $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: v2.2.4
      
      - name: Get image digest
        id: digest
        run: |
          DIGEST=$(gcloud artifacts docker images describe \
            $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG \
            --format='value(image_summary.digest)')

          echo "DIGEST=$DIGEST" >> $GITHUB_ENV

      - name: Sign Docker Image
        run: |
          cosign sign --yes \
            $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME@$DIGEST
  
  update-gitops:
    needs: build-scan-push-sign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: stackcouture/gitops-microservices-platform
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update Image Tag
        run: |
          sed -i "s|newTag:.*|newTag: ${IMAGE_TAG}|g" \
          apps/result/overlays/dev/kustomization.yaml

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add apps/result/overlays/dev/kustomization.yaml

          git commit -m "Update result-app image to ${IMAGE_TAG}" || echo "No changes"

      - name: Push Changes
        run: |
          git push
