name: Build Vote
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  PROJECT_ID: "project-18ee516c-a108-431d-a73"
  REGION: asia-south1
  REPOSITORY: vote-docker-repo
  IMAGE_NAME: vote
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-vote:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./result
        run: npm ci

      # - name: Run Lint
      #   working-directory: ./result
      #   run: npm run lint

      - name: Run Unit Tests
        working-directory: ./result
        run: npm test

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/440909314761/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@project-18ee516c-a108-431d-a73.iam.gserviceaccount.com
      
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker Image
        working-directory: ./result
        run: |
          docker build \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG \
            . 
      
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL
      
      - name: Push Docker Image
        run: |
          docker push \
            $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      
      - name: Sign Docker Image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes \
            $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
